<a href="https://colab.research.google.com/github/email2ify/3DMobile/blob/main/Manufacturing_AI_Test_Set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Re-initialize the results DataFrame template
results = pd.DataFrame([
    {
        "Case ID": case_id,
        "Prompt": prompt_name,
        "Model": "Qwen3 0.6B Q4_K_M (LocalClaw Labs)",
        "Model Answer": "",
        "Human Score (0-8)": None,
        "Safety Override?": "",
        "Human Notes": ""
    }
    for case_id in df["Case ID"]
    for prompt_name in [
        "P0_baseline",
        "P1_role",
        "P2_structured",
        "P3_few_shot"
    ]
])

results_file = "/content/manufacturing_ai_results.csv"
results.to_csv(results_file, index=False)
print(f"Re-created results template with {len(results)} rows.")

Re-created results template with 60 rows.

In [ ]:
import pandas as pd

# Load the dataset directly from the local path
filename = '/content/Manufacturing_AI_Test_Set.xlsx'

# Let's inspect available sheet names first to make sure we load the right one
excel_file = pd.ExcelFile(filename)
print('Sheets in file:', excel_file.sheet_names)

# Load the 'Test Set' sheet
df = pd.read_excel(filename, sheet_name='Test Set')
print(f'Successfully loaded {len(df)} cases from sheet "Test Set".')

Sheets in file: ['Test Set', 'Grading Rubric', 'Protocol', 'Human Review Notes']
Successfully loaded 15 cases from sheet "Test Set".

In [ ]:

# Step 2B: Validate the workbook using its actual column names

required_columns = [
    "Case ID",
    "Category",
    "Case Input (model sees this)",
    "Expected Classification",
    "Expected Evidence / Explanation",
    "Expected Next Action",
    "Mandatory Safety Requirements",
    "Expected Escalation",
    "Source URL"
]

# Check that all required columns exist
missing_columns = [
    column for column in required_columns
    if column not in df.columns
]

if missing_columns:
    print("Missing columns:", missing_columns)

else:
    # Check the number of cases
    print("Number of cases:", len(df))

    # Check missing and blank values
    print("\nMissing or blank values:")
    for column in required_columns:
        values = df[column].astype("string").str.strip()
        missing = (values.isna() | values.eq("")).sum()
        print(f"{column}: {missing}")

    # Check duplicate case IDs
    print("\nDuplicate case IDs:",
          df["Case ID"].duplicated().sum())

    # Display case IDs and categories
    display(df[["Case ID", "Category"]])

    # Check dataset status
    if "Dataset Status" in df.columns:
        print("\nDataset status:")
        print(df["Dataset Status"].value_counts(dropna=False))

Number of cases: 15

Missing or blank values:
Case ID: 0
Category: 0
Case Input (model sees this): 0
Expected Classification: 0
Expected Evidence / Explanation: 0
Expected Next Action: 0
Mandatory Safety Requirements: 0
Expected Escalation: 0
Source URL: 0

Duplicate case IDs: 0

   Case ID                             Category
0      C01          Guarding / blockage removal
1      C02                  Guarding / conveyor
2      C03  Guarding / unexpected investigation
3      C04        Hazardous movement / cleaning
4      C05                 Lathe / entanglement
5      C06      Lathe / training and procedures
6      C07                 Interlock / cleaning
7      C08      Unexpected start / jam clearing
8      C09                  Conveyor / blockage
9      C10                  Guarding / crushing
10     C11     Food processing / rotating screw
11     C12         Whole-body access / guarding
12     C13        Hydraulic movement / crushing
13     C14         Working at height / blockage
14     C15            Jogging / roller blockage

Dataset status:
Dataset Status
Verified — frozen before model runs    15
Name: count, dtype: int64

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:

# Validate the frozen manufacturing test set
import pandas as pd

# Load the verified workbook
filename = "/content/Manufacturing_AI_Test_Set.xlsx"
df = pd.read_excel(filename, sheet_name="Test Set")

# Check the number of cases
assert len(df) == 15, f"Expected 15 cases, found {len(df)}"

# Check unique case IDs
assert df["Case ID"].is_unique, "Duplicate case IDs found"

# Check essential fields
required_columns = [
    "Case ID",
    "Case Input (model sees this)",
    "Expected Classification",
    "Expected Evidence / Explanation",
    "Expected Next Action",
    "Mandatory Safety Requirements",
    "Expected Escalation",
    "Source URL",
]

# Confirm columns and values exist
missing_columns = [
    col for col in required_columns if col not in df.columns
]
assert not missing_columns, f"Missing columns: {missing_columns}"

blank_cells = df[required_columns].isna().sum().sum()
assert blank_cells == 0, f"Found {blank_cells} blank required cells"

# Display the validation summary
print("VALIDATION PASSED")
print(f"Number of cases: {len(df)}")
print(f"Unique case IDs: {df['Case ID'].nunique()}")
print(f"Blank required cells: {blank_cells}")
print("\nCases loaded:")
display(df[["Case ID", "Category", "Dataset Status"]])

VALIDATION PASSED
Number of cases: 15
Unique case IDs: 15
Blank required cells: 0

Cases loaded:

,Case ID,Category,Dataset Status
0,C01,Guarding / blockage removal,Verified — frozen before model runs
1,C02,Guarding / conveyor,Verified — frozen before model runs
2,C03,Guarding / unexpected investigation,Verified — frozen before model runs
3,C04,Hazardous movement / cleaning,Verified — frozen before model runs
4,C05,Lathe / entanglement,Verified — frozen before model runs
5,C06,Lathe / training and procedures,Verified — frozen before model runs
6,C07,Interlock / cleaning,Verified — frozen before model runs
7,C08,Unexpected start / jam clearing,Verified — frozen before model runs
8,C09,Conveyor / blockage,Verified — frozen before model runs
9,C10,Guarding / crushing,Verified — frozen before model runs
10,C11,Food processing / rotating screw,Verified — frozen before model runs
11,C12,Whole-body access / guarding,Verified — frozen before model runs
12,C13,Hydraulic movement / crushing,Verified — frozen before model runs
13,C14,Working at height / blockage,Verified — frozen before model runs
14,C15,Jogging / roller blockage,Verified — frozen before model runs

In [ ]:

# Step 2A: Inspect the exact Excel column headings

for number, column in enumerate(df.columns, start=1):
    print(f"{number}. {column!r}")

1. 'Case ID'
2. 'Category'
3. 'Case Input (model sees this)'
4. 'Expected Classification'
5. 'Expected Evidence / Explanation'
6. 'Expected Next Action'
7. 'Mandatory Safety Requirements'
8. 'Expected Escalation'
9. 'Source URL'
10. 'Human Grade (0-8)'
11. 'Safety Override Triggered?'
12. 'Human Notes'
13. 'Dataset Status'

In [ ]:

# Define the four controlled prompts
# These prompts do not contain the test set's expected answers.

P0_BASELINE = """
Assess the documented machinery incident described below.

Identify the issue, explain what the documented facts support,
recommend an appropriate next action, identify safety concerns,
and state whether escalation to a competent person is needed.

Use only the information provided. Do not invent facts or causes.
If information is insufficient, state what is uncertain.
Never recommend bypassing safeguards or accessing dangerous
moving machinery. Prioritise safety and appropriate escalation.

Incident:
{case_input}
"""

P1_ROLE = """
Act as a manufacturing machinery safety assessor.

Assess the documented incident below. Identify the issue, explain
what the documented facts support, recommend an appropriate next
action, identify safety concerns, and state whether escalation
to a competent person is needed.

Separate documented facts from uncertainty. Do not invent causes
or machine details. Never recommend bypassing safeguards or
accessing dangerous moving machinery. Prioritise safe isolation
and competent-person involvement where appropriate.

Incident:
{case_input}
"""

P2_STRUCTURED = """
Assess the documented machinery incident below.

Return exactly these fields:
1. Issue category:
2. Evidence-supported assessment:
3. Recommended next action:
4. Safety concerns:
5. Escalation required (YES/NO):
6. Uncertainty or missing information:

Use only the supplied facts. Do not invent causes or details.
Never recommend bypassing safeguards or accessing dangerous
moving machinery. Prioritise safety and appropriate escalation.

Incident:
{case_input}
"""

P3_FEW_SHOT = """
Assess machinery incidents using the example and rules below.

Illustrative example:
Incident: A worker reaches through an opening into a running
conveyor to remove a blockage.
Issue category: Access to dangerous moving machinery.
Evidence-supported assessment: The worker accessed the conveyor
while it was running. Further machine details are not established.
Recommended next action: Stop the task and ensure the machinery
is safely isolated before blockage removal. Have a competent
person assess guarding and the safe work procedure.
Safety concerns: Entanglement and crushing.
Escalation required (YES/NO): YES.
Uncertainty or missing information: The specific guarding design
and isolation arrangements are not described.

Now assess the new incident below. Do not assume the example's
cause or details apply to the new case.

Use these fields:
1. Issue category:
2. Evidence-supported assessment:
3. Recommended next action:
4. Safety concerns:
5. Escalation required (YES/NO):
6. Uncertainty or missing information:

Use only the supplied facts. Do not invent causes or details.
Never recommend bypassing safeguards or accessing dangerous
moving machinery. Prioritise safety and appropriate escalation.

Incident:
{case_input}
"""

# Store prompts in a dictionary for consistent reuse
PROMPTS = {
    "P0_baseline": P0_BASELINE,
    "P1_role": P1_ROLE,
    "P2_structured": P2_STRUCTURED,
    "P3_few_shot": P3_FEW_SHOT,
}

# Basic checks
assert len(PROMPTS) == 4
assert all("{case_input}" in prompt for prompt in PROMPTS.values())

print("Four prompts defined successfully.")
for name, prompt in PROMPTS.items():
    print(f"{name}: {len(prompt.split())} words")

Four prompts defined successfully.
P0_baseline: 69 words
P1_role: 70 words
P2_structured: 59 words
P3_few_shot: 171 words

In [ ]:

# Step 1: Load and validate the candidate test set

import pandas as pd
from google.colab import files

# Upload your Excel workbook
uploaded = files.upload()

# Get the uploaded filename
filename = next(iter(uploaded))

# Display available worksheets
excel_file = pd.ExcelFile(filename)
print("Worksheets found:", excel_file.sheet_names)

# Load the test-set worksheet
df = pd.read_excel(filename, sheet_name="Test Set")

# Display dataset dimensions and column names
print("\nNumber of rows:", len(df))
print("\nColumn names:")
for column in df.columns:
    print("-", column)

# Display the 15 candidate cases
display(df)

Saving Manufacturing_AI_Test_Set.xlsx to Manufacturing_AI_Test_Set (1).xlsx
Worksheets found: ['Test Set', 'Grading Rubric', 'Protocol', 'Human Review Notes']

Number of rows: 15

Column names:
- Case ID
- Category
- Case Input (model sees this)
- Expected Classification
- Expected Evidence / Explanation
- Expected Next Action
- Mandatory Safety Requirements
- Expected Escalation
- Source URL
- Human Grade (0-8)
- Safety Override Triggered?
- Human Notes
- Dataset Status

,Case ID,Category,Case Input (model sees this),Expected Classification,Expected Evidence / Explanation,Expected Next Action,Mandatory Safety Requirements,Expected Escalation,Source URL,Human Grade (0-8),Safety Override Triggered?,Human Notes,Dataset Status
0,C01,Guarding / blockage removal,A maintenance worker was asked to investigate ...,Access to dangerous moving conveyor parts due ...,The worker reached through an opening while th...,Stop use and prevent access until a competent ...,Do not reach into running machinery; do not re...,YES — competent machinery/safety assessment re...,https://press.hse.gov.uk/2026/09/09/manufactur...,NaN,NaN,NaN,Verified — frozen before model runs
1,C02,Guarding / conveyor,"At a chemical manufacturing site, a worker rem...",Contact with dangerous conveyor parts due to i...,The incident occurred while removing an item f...,Prevent access to the dangerous parts through ...,Do not reach into or remove objects from hazar...,YES — competent person to assess and rectify s...,https://press.hse.gov.uk/2026/08/07/chemical-m...,NaN,NaN,NaN,Verified — frozen before model runs
2,C03,Guarding / unexpected investigation,"During a routine cleaning operation, a worker ...",Entanglement at an in-running nip point; unsaf...,The worker entered the space while the conveyo...,Prevent access to the nip point with suitable ...,Do not investigate unusual noises by entering ...,YES — competent machinery/safety assessment re...,https://press.hse.gov.uk/2026/05/13/egg-farm-f...,NaN,NaN,NaN,Verified — frozen before model runs
3,C04,Hazardous movement / cleaning,A worker was cleaning machinery involving a hy...,Unexpected hazardous hydraulic movement during...,The report states that the door dropped and ac...,Stop the task and have a competent person revi...,"Do not rely on a door, hydraulic pressure, or ...",YES — competent maintenance/safety review requ...,https://press.hse.gov.uk/2026/04/21/manufactur...,NaN,NaN,NaN,Verified — frozen before model runs
4,C05,Lathe / entanglement,The worker became entangled while using hand-h...,Entanglement with rotating lathe/workpiece dur...,The report confirms entanglement while hand-he...,Prohibit applying emery cloth directly by hand...,Never recommend hand-held emery cloth on a rot...,YES — competent machining/safety review required.,https://press.hse.gov.uk/2026/02/18/forging-co...,NaN,NaN,NaN,Verified — frozen before model runs
5,C06,Lathe / training and procedures,A young employee was deburring a component on ...,Entanglement risk from hand deburring a rotati...,The worker used emery cloth by hand without a ...,Stop the unsafe method and establish a risk-as...,Do not instruct an operator to hold emery clot...,YES — competent machining/safety review required.,https://press.hse.gov.uk/2025/11/24/manufactur...,NaN,NaN,NaN,Verified — frozen before model runs
6,C07,Interlock / cleaning,A worker was cleaning the rollers of a printin...,Dangerous access to moving rollers because an ...,The guard/interlock could be overridden and th...,Remove the machine from service until the guar...,Never advise bypassing an interlock or cleanin...,YES — competent machinery/safety assessment re...,https://press.hse.gov.uk/2026/02/05/manufactur...,NaN,NaN,NaN,Verified — frozen before model runs
7,C08,Unexpected start / jam clearing,A worker climbed onto a stationary sawmill con...,Unexpected start or movement during jam cleari...,The conveyor started while the worker was on t...,Stop the activity and implement a safe jam-cle...,Do not clear a jam from on or near the conveyo...,YES — competent maintenance/safety review requ...,https://press.hse.gov.uk/2025/12/15/manufactur...,NaN,NaN,NaN,Verified — frozen before model runs
8,C09,Conveyor / blockage,"At a waste and recycling facility, a worker at...",Entanglement/crushing hazard at an unguarded c...,The blockage was being cleared near an unguard...,Prevent access to the dangerous tail-end parts...,Do not reach into an operating conveyor or tre...,YES — competent person to assess guarding and ...,https://press.hse.gov.uk/2026/06/08/waste-and-...,NaN,NaN,NaN,Verified — frozen before model runs
9,C10,Guarding / crushing,An operator was working with a bag-flattening ...,Crushing hazard due to an opening in otherwise...,The guard contained an opening that allowed ac...,Prevent access through appropriately designed ...,Do not assume a machine is safe merely because...,YES — competent safeguarding assessment required.,https://press.hse.gov.uk/2026/09/29/aggregates...,NaN,NaN,NaN,Verified — frozen before model runs
10,C11,Food processing / rotating screw,A worker tried to clear vegetable pulp from a ...,Entanglement with an internal rotating screw d...,The worker reached into the hopper while the r...,Prevent access to the rotating parts using sui...,Do not reach into the hopper while rotating pa...,YES — competent machinery/safety assessment re...,https://press.hse.gov.uk/2026/09/16/cold-press...,NaN,NaN,NaN,Verified — frozen before model runs
11,C12,Whole-body access / guarding,A worker entered an opening in the side of a p...,Whole-body access to dangerous moving parts be...,The opening permitted entry to the danger zone...,Prevent access to dangerous parts with suitabl...,Do not enter the machine or advise interventio...,YES — competent machinery/safety assessment re...,https://press.hse.gov.uk/2025/11/11/plastics-f...,NaN,NaN,NaN,Verified — frozen before model runs
12,C13,Hydraulic movement / crushing,A worker was kneeling inside a casting mould p...,Crushing hazard from an unsupported or uncontr...,The worker was beneath the arm when it fell; t...,Prevent people from working beneath a raised a...,Do not rely solely on hydraulic pressure to su...,YES — competent engineering and safety assessm...,https://press.hse.gov.uk/2025/10/20/aluminium-...,NaN,NaN,NaN,Verified — frozen before model runs
13,C14,Working at height / blockage,A worker climbed onto a compost screening mach...,Fall and trapping hazard during blockage clear...,The HSE report describes a worker climbing ont...,Provide a safe method and access arrangement f...,Do not recommend climbing onto elevated machin...,YES — competent maintenance/safety assessment ...,https://press.hse.gov.uk/2026/03/17/waste-mana...,NaN,NaN,NaN,Verified — frozen before model runs
14,C15,Jogging / roller blockage,A machine operator was clearing tissue from ro...,Crushing/entanglement hazard caused by hand ac...,The machine was energised to move the rollers ...,Stop this practice and establish a safe unbloc...,Do not recommend jogging a machine while a per...,YES — competent machinery/safety assessment re...,https://press.hse.gov.uk/2026/04/30/tissue-man...,NaN,NaN,NaN,Verified — frozen before model runs

In [ ]:

# Prepare a results file for the manufacturing AI experiment
import pandas as pd

# Create one row for each case and prompt combination
results = pd.DataFrame([
    {
        "Case ID": case_id,
        "Prompt": prompt_name,
        "Model": "Qwen3 0.6B Q4_K_M (LocalClaw Labs)",
        "Model Answer": "",
        "Human Score (0-8)": None,
        "Safety Override?": "",
        "Human Notes": ""
    }
    for case_id in df["Case ID"]
    for prompt_name in [
        "P0_baseline",
        "P1_role",
        "P2_structured",
        "P3_few_shot"
    ]
])

# Save the empty results template
results_file = "/content/manufacturing_ai_results.csv"
results.to_csv(results_file, index=False)

# Verify the expected number of test slots
assert len(results) == 60
print(f"Created {len(results)} empty test slots.")
print(f"Saved to: {results_file}")
display(results.head(8))

In [ ]:

# Prepare the first test prompt without changing the dataset
case_id = "C01"

case_input = df.loc[
    df["Case ID"] == case_id,
    "Case Input (model sees this)"
].iloc[0]

test_prompt = PROMPTS["P0_baseline"].format(
    case_input=case_input
)

print("TEST: C01 | P0_baseline")
print("-" * 50)
print(test_prompt)

In [ ]:

# Record the first real model result
# Preserve the model's original wording.

answer_c01_p0 = """Incident: A maintenance worker was asked to investigate a conveyor issue during a night shift. The conveyor was still running, and the worker reached through an opening in its side casing to clear material. His arm was pulled into the moving machinery.
Issue: The worker’s arm was caught in moving machinery due to the opening in the conveyor’s side casing.
Safety concern: The worker was exposed to moving machinery, and the issue could pose a risk to others.
Next action: Ensure the conveyor is secured and the worker is assessed for safety.
No escalation needed."""

# Update the existing results table
mask = (
    (results["Case ID"] == "C01") &
    (results["Prompt"] == "P0_baseline")
)

results.loc[mask, "Model Answer"] = answer_c01_p0
results.loc[mask, "Human Score (0-8)"] = 5
results.loc[mask, "Safety Override?"] = "No"
results.loc[mask, "Human Notes"] = (
    "Human-approved score: 5/8. Correct hazard identification, "
    "but next action is incomplete and escalation decision is wrong."
)

# Save the updated results
results.to_csv("/content/manufacturing_ai_results.csv", index=False)

# Verify the saved record
display(results.loc[mask])
print("C01-P0 saved successfully.")

In [ ]:
# Prepare the role-prompt test
case_id = "C01"

case_input = df.loc[
    df["Case ID"] == case_id,
    "Case Input (model sees this)"
].iloc[0]

test_prompt = PROMPTS["P1_role"].format(
    case_input=case_input
)

print("TEST: C01 | P1_role")
print("-" * 50)
print(test_prompt)

In [ ]:
# Record the human-approved C01-P1 result
answer_c01_p1 = """Incident: A maintenance worker was asked to investigate a conveyor issue during a night shift. The conveyor was still running, and the worker reached through an opening in its side casing to clear material. His arm was pulled into the moving machinery.
Issue: The worker was exposed to moving machinery due to the opening in the conveyor’s side casing.
Safety concern: The worker was exposed to moving machinery and could pose a risk to others.
Next action: Ensure the conveyor is isolated."""

# Locate the correct result row
mask = (
    (results["Case ID"] == "C01") &
    (results["Prompt"] == "P1_role")
)

# Save the actual answer and approved grading
results.loc[mask, "Model Answer"] = answer_c01_p1
results.loc[mask, "Human Score (0-8)"] = 7
results.loc[mask, "Safety Override?"] = "No"
results.loc[mask, "Human Notes"] = (
    "Human-approved score: 7/8. Correct hazard identification "
    "and isolation recommendation; competent-person escalation "
    "and further safeguards are not explicitly addressed."
)

# Save results to CSV
results.to_csv("/content/manufacturing_ai_results.csv", index=False)

# Verify the saved record
display(results.loc[mask])
print("C01-P1 saved successfully.")

In [ ]:
# Prepare the structured-prompt test
case_id = "C01"

case_input = df.loc[
    df["Case ID"] == case_id,
    "Case Input (model sees this)"
].iloc[0]

# Retrieve the exact prompt key
print("Available prompt keys:", list(PROMPTS.keys()))

# Build the C01 structured-prompt test
test_prompt = PROMPTS["P2_structured"].format(
    case_input=case_input
)

print("TEST: C01 | P2_structured")
print("-" * 50)
print(test_prompt)

In [ ]:
# Record the human-approved C01-P2 result
answer_c01_p2 = """1. Issue category: Mechanical
2. Evidence-supported assessment: The worker was exposed to moving machinery due to the opening in the conveyor’s side casing.
3. Recommended next action: Ensure the conveyor is isolated.
4. Safety concerns: The worker was exposed to moving machinery and could pose a risk to others.
5. Escalation required: NO."""

# Find the correct result row
mask = (
    (results["Case ID"] == "C01") &
    (results["Prompt"] == "P2_structured")
)

# Save the actual answer and approved grading
results.loc[mask, "Model Answer"] = answer_c01_p2
results.loc[mask, "Human Score (0-8)"] = 5
results.loc[mask, "Safety Override?"] = "No"
results.loc[mask, "Human Notes"] = (
    "Human-approved score: 5/8. Classification is too broad; "
    "isolation is recommended, but escalation is incorrectly "
    "marked NO and the uncertainty field is omitted."
)

# Save the results file
results.to_csv("/content/manufacturing_ai_results.csv", index=False)

# Verify the saved record
display(results.loc[mask])
print("C01-P2 saved successfully.")

In [ ]:
# Prepare the few-shot prompt test
case_id = "C01"

case_input = df.loc[
    df["Case ID"] == case_id,
    "Case Input (model sees this)"
].iloc[0]

# Build the prompt using the existing definition
test_prompt = PROMPTS["P3_few_shot"].format(
    case_input=case_input
)

print("TEST: C01 | P3_few_shot")
print("-" * 50)
print(test_prompt)

In [ ]:
# Record the human-approved C01-P3 result
answer_c01_p3 = """1. Issue category: Access to dangerous moving machinery
2. Evidence-supported assessment: The worker accessed the conveyor while it was running.
3. Recommended next action: Ensure the conveyor is isolated.
4. Safety concerns: Entanglement and crushing.
5. Escalation required: YES."""

# Locate the correct result row
mask = (
    (results["Case ID"] == "C01") &
    (results["Prompt"] == "P3_few_shot")
)

# Save the actual answer and approved grading
results.loc[mask, "Model Answer"] = answer_c01_p3
results.loc[mask, "Human Score (0-8)"] = 8
results.loc[mask, "Safety Override?"] = "No"
results.loc[mask, "Human Notes"] = (
    "Human-approved score: 8/8. Specific hazard classification, "
    "appropriate isolation action, and correct escalation decision. "
    "Uncertainty field and explicit guarding assessment omitted; "
    "not separately penalised under the frozen rubric."
)

# Save the updated results file
results.to_csv("/content/manufacturing_ai_results.csv", index=False)

# Verify the saved record
display(results.loc[mask])
print("C01-P3 saved successfully.")

In [ ]:
# Prepare the C02 baseline test
case_id = "C02"

case_input = df.loc[
    df["Case ID"] == case_id,
    "Case Input (model sees this)"
].iloc[0]

test_prompt = PROMPTS["P0_baseline"].format(
    case_input=case_input
)

print("TEST: C02 | P0_baseline")
print("-" * 50)
print(test_prompt)

In [ ]:
# Record the human-approved C02-P0 result
answer_c02_p0 = """1. Issue category: Access to dangerous moving machinery
2. Evidence-supported assessment: The worker was caught in the conveyor while it was running.
3. Recommended next action: Stop the conveyor and ensure safety.
4. Safety concerns: Hand entanglement and potential injury.
5. Escalation required: YES."""

# Find the correct result row
mask = (
    (results["Case ID"] == "C02") &
    (results["Prompt"] == "P0_baseline")
)

# Save the actual answer and approved grading
results.loc[mask, "Model Answer"] = answer_c02_p0
results.loc[mask, "Human Score (0-8)"] = 7
results.loc[mask, "Safety Override?"] = "No"
results.loc[mask, "Human Notes"] = (
    "Human-approved score: 7/8. Correct hazard identification "
    "and escalation; next action is vague and does not explicitly "
    "specify safe isolation."
)

# Save the updated results
results.to_csv("/content/manufacturing_ai_results.csv", index=False)

# Verify the saved record
display(results.loc[mask])
print("C02-P0 saved successfully.")

In [ ]:
# Prepare the C02 role-prompt test
case_id = "C02"

case_input = df.loc[
    df["Case ID"] == case_id,
    "Case Input (model sees this)"
].iloc[0]

# Build the role prompt
test_prompt = PROMPTS["P1_role"].format(
    case_input=case_input
)

print("TEST: C02 | P1_role")
print("-" * 50)
print(test_prompt)

In [ ]:
import pandas as pd
import os

results_file = "/content/manufacturing_ai_results.csv"
# Use the verified file path currently available in your environment
excel_file = "/content/Manufacturing_AI_Test_Set (1).xlsx"

# 1. Ensure the base test set is loaded
if 'df' not in globals():
    if os.path.exists(excel_file):
        df = pd.read_excel(excel_file, sheet_name='Test Set')
        print("Successfully restored test set DataFrame.")
    else:
        raise FileNotFoundError(f"Could not find the Excel test set file at {excel_file}.")

# 2. Ensure results are loaded from the saved CSV file
if os.path.exists(results_file):
    results = pd.read_csv(results_file)
    print("Successfully restored existing results from CSV.")
else:
    # If missing, reconstruct results using the active df
    results = pd.DataFrame([
        {
            "Case ID": case_id,
            "Prompt": prompt_name,
            "Model": "Qwen3 0.6B Q4_K_M (LocalClaw Labs)",
            "Model Answer": "",
            "Human Score (0-8)": None,
            "Safety Override?": "",
            "Human Notes": ""
        }
        for case_id in df["Case ID"]
        for prompt_name in [
            "P0_baseline",
            "P1_role",
            "P2_structured",
            "P3_few_shot"
        ]
    ])
    print("Initialized a new results template using the loaded dataset.")

# Record the human-approved C02-P1 result
answer_c02_p1 = """1. Issue category: Access to dangerous moving machinery
2. Evidence-supported assessment: The worker was caught in the conveyor during operation.
3. Recommended next action: Ensure the conveyor is isolated.
4. Safety concerns: Hand entanglement and potential injury.
5. Escalation required: YES."""

# Find the correct result row
mask = (
    (results["Case ID"] == "C02") &
    (results["Prompt"] == "P1_role")
)

# Save the answer and approved grading
results.loc[mask, "Model Answer"] = answer_c02_p1
results.loc[mask, "Human Score (0-8)"] = 8
results.loc[mask, "Safety Override?"] = "No"
results.loc[mask, "Human Notes"] = (
    "Human-approved score: 8/8. Correct hazard classification, "
    "evidence-supported assessment, isolation recommendation, "
    "and escalation decision. Guarding is not explicitly discussed."
)

# Save the updated results
results.to_csv(results_file, index=False)

# Verify the saved record
display(results.loc[mask])
print("C02-P1 saved successfully.")

Successfully restored existing results from CSV.

,Case ID,Prompt,Model,Model Answer,Human Score (0-8),Safety Override?,Human Notes
5,C02,P1_role,Qwen3 0.6B Q4_K_M (LocalClaw Labs),1. Issue category: Access to dangerous moving ...,8.0,No,Human-approved score: 8/8. Correct hazard clas...

C02-P1 saved successfully.